---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: djudorange/node-gulp-mocha
    tag: "latest"

inputs:
- name: sample_node

run:
  path: sample_node/blue-green-app-deployment/ci/tasks/run-unit-tests
